# Copyright (c) 2016-2017 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: 'ElecFreaks Learn-en'
site_description: 'ElecFreaks Product Document'
site_author: 'Will'
site_url: 'https://www.elecfreaks.com/learn-en/'

# Repository
repo_name: 'Microbit'
repo_url: 'https://github.com/elecfreaks/learn-en'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 ElecFreaks'

# Theme directory
theme_dir: material

# Icon
#site_favicon: 'docs/images/favicon.ico'
site_favicon: https://raw.githubusercontent.com/elecfreaks/learn-en/master/docs/images/favicon.ico

# Configuration
theme:
  name: 'material'
  feature:
    tabs: false
  palette:
    primary: light green
    accent: 'indigo'    
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'images/favicon.ico'
  search:
    language: 'en'
    tokenizer: '[\s\-\.]+'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/elecfreaks/learn-en'
    - type: 'facebook'
      link: 'https://www.facebook.com/ElecFreaksTech/'
    #- type: 'linkedin'
    #  link: 'https://linkedin.com/in/squidfunk'


# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite(guess_lang=false)
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
  - pymdownx.keys

# Page tree
pages:
  - ElecFreaks Learn: 'index.md'
  - micro:bit Basic Tutorial:
    - BBC micro:bit: micro_bit.md
    - micro:bit Funny Classroom Series:
      - Flashing Heart: classroom_case_01.md
      - Smiley Buttons: classroom_case_02.md
      - Love Meter: classroom_case_03.md
      - Rock Papaer Scissors: classroom_case_04.md
      - Magic Button Trick: classroom_case_05.md
      - Coin Flipper: classroom_case_06.md
      - Salute: classroom_case_07.md
      - Hack your headphones: classroom_case_08.md
      - Banana Keyboard: classroom_case_09.md
      - Guitar: classroom_case_10.md
      - Duct Type Wallet: classroom_case_11.md
      - Watch: classroom_case_12.md
      - Countdown Timer: classroom_case_13.md
      - Digital Watch: classroom_case_14.md
      - Soil Moisture: classroom_case_15.md
      - Plant Watering: classroom_case_16.md
      - Reaction Time: classroom_case_17.md
      - States of Matter: classroom_case_18.md
      - Mood Radio: classroom_case_19.md
      - Tele-Potato: classroom_case_20.md
      - Hot or Cold: classroom_case_21.md
      - Voting Machine: classroom_case_22.md
      - Infection: classroom_case_23.md
      - Fireflies: classroom_case_24.md
      - Rock Paper Scissors Teams: classroom_case_25.md
      - Microcoin: classroom_case_26.md
      - Inchworm: classroom_case_27.md
      - Milk Monster: classroom_case_28.md
      - RC Car: classroom_case_29.md
      - Timing Gates: classroom_case_30.md
      - Compass: classroom_case_31.md
      - Telegraph: classroom_case_32.md
      - Railway Crossing: classroom_case_33.md
      - Karel: classroom_case_34.md
  - micro:bit relevant materials:
    - Edge Connector Data Sheet: Edge_Connector_Data_Sheet.md
    - How to Use Bluetooth(IOS System): How_to_Use_Bluetooth_IOS_System.md
    - troubleshooting downloads with webusb: troubleshooting_downloads_with_webusb.md
    - ring_bit_car_v2_accelerometer_arithmetic.md
  - micro:bit Kits:
    - micro:bit Watch Kit:
      - Introduction: watch_kit.md
      - Power:bit Introduction: power_bit.md
      - Case 01：Compass: watch_kit_case_01.md
      - Case 02：Dice: watch_kit_case_02.md
      - Case 03：Thermometer: watch_kit_case_03.md
      - Case 04：Timer: watch_kit_case_04.md
      - Case 05：Flashlight: watch_kit_case_05.md   
    - micro:bit Basic Kit:
      - Introduction: basic_kit.md
      - Basic:bit Introduction: basic_bit.md
      - Case 01 Light Controller: basic_kit_case_01.md
      - Case 02 Morse Code: basic_kit_case_02.md
      - Case 03 Function Selector: basic_kit_case_03.md
      - Case 04 Show Box for Stickers: basic_kit_case_04.md
      - Case 05 Shock Box: basic_kit_case_05.md

      

    - micro:bit Starter Kit:
      - Introduction: starter_kit.md
      - Breadboard:bit Introduction: breadboard_bit.md
      - Lesson 01 LED: starter_kit_case_01.md
      - Lesson 02 Button: starter_kit_case_02.md
      - Lesson 03 Trimpot: starter_kit_case_03.md
      - Lesson 04 Photocell: starter_kit_case_04.md
      - Lesson 05 RGB LED: starter_kit_case_05.md
      - Lesson 06 Self-lock Switch: starter_kit_case_06.md
      - Lesson 07 Temperature Sensor: starter_kit_case_07.md
      - Lesson 08 Servo: starter_kit_case_08.md
      - Lesson 09 Buzzer: starter_kit_case_09.md
      - Lesson 10 Motor: starter_kit_case_10.md
      - Lesson 11 Rainbow LED: starter_kit_case_11.md
      - Lesson 12 Accelerometer: starter_kit_case_12.md
      - Lesson 13 Compass: starter_kit_case_13.md
      - Lesson 14 Ambient Light: starter_kit_case_14.md
    - micro:bit Tinker Kit: 
      - Introduction: tinker_kit.md
      - Octopus:bit Introduction: octopus_bit.md
      - Case 01 Music Machine: tinker_kit_case_01.md
      - Case 02 Smart Light: tinker_kit_case_02.md
      - Case 03 Electro-Theremin: tinker_kit_case_03.md
      - Case 04 Simple Alarm Box: tinker_kit_case_04.md
      - Case 05 Plant Monitoring Device: tinker_kit_case_05.md
      - Case 06 Intruder Detection: tinker_kit_case_06.md
      - Case 07 Fish Feeder: tinker_kit_case_07.md
      - Case 08 Motion Detector: tinker_kit_case_08.md
      - Case 09 Lie Detector: tinker_kit_case_09.md
      - Case 10 PADDLEBALLSUPERSMASHEM: tinker_kit_case_10.md
      - Case 11 Avoid Asteroids: tinker_kit_case_11.md
      - Case 12 Remote Control Everything: tinker_kit_case_12.md
      - Case 13 micro:bit Car: tinker_kit_case_13.md
      - Case 14 Flipping Pancakes: tinker_kit_case_14.md
      - Case 15 Maze Runner: tinker_kit_case_15.md
      - Case 16 QUICK MATHS: tinker_kit_case_16.md
      - Case 17 Pitch Perfect: tinker_kit_case_17.md
      - Case 18 Finger Dexterity: tinker_kit_case_18.md
      - Case 19 Electric Spirit Level: tinker_kit_case_19.md
      - Case 20 Space Shooter: tinker_kit_case_20.md
      - Case 21 Flappy Bird: tinker_kit_case_21.md
      - Case 22 Wire Transmission: tinker_kit_case_22.md
      - Case 23 Snake Game: tinker_kit_case_23.md
      - Case 24 Game bit: tinker_kit_case_24.md
      - Case 25 µ reMorse: tinker_kit_case_25.md
      - Case 26 Coin Sorter with micro:bit: tinker_kit_case_26.md
      - Case 27 Make a Waving Fortune Cat: tinker_kit_case_27.md
      - Case 28 Put together the Krazy Kar v2: tinker_kit_case_28.md
      - Case 29 Shoot Em Up Kit: tinker_kit_case_29.md
      - Case 30 Reaction Time Tester: tinker_kit_case_30.md
      - case 31 morse code transmitter: tinker_kit_case_31.md
      - case 32 reclusebot: tinker_kit_case_32.md

    - micro:bit Smart home Kit:
      - Introduction: smart_home_kit.md
      - sensor:bit Introduction: sensor_bit.md
      - Case 01 Voice-activated Lights: smart_home_case_01.md
      - Case 02 Smart Fan: smart_home_case_02.md
      - Case 03 Auto Windows: smart_home_case_03.md
      - Case 04 Smart Wardrobe: smart_home_case_04.md
      - Case 05 Water Level Alarming: smart_home_case_05.md
      - case 06 smart telecontrol door opener: smart_home_case_06.md
      - case 07 smart decibel tester: smart_home_case_07.md
      - case 08 simple spirometer: smart_home_case_08.md
      - case 09 lie detector: smart_home_case_09.md
      - case 10 simple alarm box: smart_home_case_10.md
      - case 11 intruder detection system: smart_home_case_11.md
    - micro:bit experiment box kit:
      - introduction: experiment_box.md
      - circuit knowledge: experiment_box_circuit_knowledge.md
      - case 01 led: experiment_box_case_01.md
      - case 02 button: experiment_box_case_02.md
      - case 03 RGB led: experiment_box_case_03.md
      - case 04 trimpot: experiment_box_case_04.md
      - case 05 photocell: experiment_box_case_05.md
      - case 06 NTC: experiment_box_case_06.md
      - case 07 buzzer: experiment_box_case_07.md
      - case 08 servo: experiment_box_case_08.md
      - case 09 self-locking button: experiment_box_case_09.md
      - case 10 rainbow led ring: experiment_box_case_10.md
      - case 11 DC motor: experiment_box_case_11.md
      - circuit design 01: experiment_box_circuit_case_01.md
      - circuit design 02: experiment_box_circuit_case_02.md
    - ring:bit Car Kit: 
      - Introduction: ring_bit_car.md
      - Ring:bit Introduction: ring_bit.md
      - Case 01 Add Package: ring_bit_car_case_01.md
      - Case 02 S Walk: ring_bit_car_case_02.md
      - Case 03 Draw a Circel: ring_bit_car_case_03.md
      - Case 04 Wireless Remote Control: ring_bit_car_case_04.md
      - Case 05 Crazy dance: ring_bit_car_case_05.md
      - Case 06 Turns over Detection: ring_bit_car_case_06.md
      - Case 07 Light Follow: ring_bit_car_case_07.md
      - Case 08 Remote Control by an accelerometer: ring_bit_car_case_08.md
    - ring:bit Car Kit V2: 
      - Introduction: ring_bit_car_v2.md
      - Ring:bit Car Assembly Step: ring_bit_car_v2_assembly_step.md
      - Ring:bit Introduction: ring_bit_v2.md
      - Ring:bit Introduction of E-blocks: ring_bit_car_v2_extensions.md
      - Case 01 Full speed ahead: ring_bit_car_v2_case_01.md
      - Case 02 Make a shape: ring_bit_car_v2_case_02.md
      - Case 03 Turn at an angle: ring_bit_car_v2_case_03.md
      - Case 04 Here comes the police: ring_bit_car_v2_case_04.md
      - Case_05 Crazy dance: ring_bit_car_v2_case_05.md
      - Case_06 Remote Control: ring_bit_car_v2_case_06.md
      - Case_07 Turns over Detection : ring_bit_car_v2_case_07.md
      - Case_08 Light Follow: ring_bit_car_v2_case_08.md
      - Case_09 Remote Control by an accelerometer: ring_bit_car_v2_case_09.md
    - motor:bit Smart Car Kit: 
      - Introduction: motor_bit_smart_car.md
      - motor:bit Introduction: motor_bit_v16.md
      - Case 01 Fixed Parking: motor_bit_smart_car_case_01.md
      - Case 02 Keep Distance: motor_bit_smart_car_case_02.md
      - Case 03 Line Tracking: motor_bit_smart_car_case_03.md
      - Case 04 Avoid Barrier: motor_bit_smart_car_case_04.md
      - Case 05 Remote Control: motor_bit_smart_car_case_05.md
      - Case 06 Bluetooth Control: motor_bit_smart_car_case_06.md  
    - robit Smart Car kit: 
      - Kit Introduction: robit_smart_car.md
      - robit Introduction: robit.md
      - Case 01 Ultrasonic Distance Measurement: robit_case_01.md
      - Case 02 Ultrasonic Obstacle Avoidance: robit_case_02.md
      - Case 03 Never Fallen Car: robit_case_03.md
      - Case 04 Line Tracking: robit_case_04.md
      - Case 05 Reversing Alarm: robit_case_05.md
      - Case 06 Rainbow LED: robit_case_06.md
      - Case 07 Smart Car Light: robit_case_07.md
  - micro:bit Modules and Sensor:
    - sensor:bit: sensor_bit.md
    - motor:bit v14: motor_bit_v14.md
    - joystick:bit v2: joystick_bit_v2.md
    - robit: robit.md
    - edge:bit: edge_bit.md
    - joystick:bit: joystick_bit.md
    - Power Supply: microbit_power_supply.md
    - sonar:bit: sonar_bit.md
    - Analog Rotation Brick: octopus_ef04085.md
    - 3V Relay Module: octopus_ef04086.md
    - BME280 Air Pressure Sensor: octopus_ef04087.md
    - 8x16 matrix module: octopus_ef03418.md
    - Tracking Module: octopus_ef04088.md    
    - Octopus PM2.5 module: octopus_ef04090.md    
    - Octopus Single RGB Rainbow LED: octopus_ef04091.md
    - 3V vertical water pump: 3V_vertical_water_pump.md
    - christmas tree rainbow led: christmas_tree_rainbow_led.md
    - snowflake buzzer: snowflake_buzzer.md      


# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'
